title: Sebastian Luber
logo: /assets/Picture1.jpg
description: PhD. Financial Economics, CBS/UCLA
#show_downloads: true
theme: jekyll-theme-minimal
---

![Sebastian Luber](/assets/Picture1.jpg){:style="width:50%;"}
