title: Sebastian Luber
logo: /assets/Picture1.jpg
description: "Ph.D. in Finance, CBS/UCLA"
<a href="/">View My LinkedIn Profile</a> 
show_downloads: true
theme: jekyll-theme-minimal
---

![Sebastian Luber](/assets/Picture1.jpg){:style="width:50%;"}
